# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/falque/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/222.4345.21/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/falque/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/222.4345.21/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/falque/Travail/Doctorat/CP/Workspace/XCSP3-CPP-Parser

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/falque/Travail/Doctorat/CP/Workspace/XCSP3-CPP-Parser

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/falque/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/222.4345.21/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/falque/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/222.4345.21/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/falque/Travail/Doctorat/CP/Workspace/XCSP3-CPP-Parser/CMakeFiles /home/falque/Travail/Doctorat/CP/Workspace/XCSP3-CPP-Parser//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/falque/Travail/Doctorat/CP/Workspace/XCSP3-CPP-Parser/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named xcsp3parser

# Build rule for target.
xcsp3parser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xcsp3parser
.PHONY : xcsp3parser

# fast build rule for target.
xcsp3parser/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser.dir/build.make CMakeFiles/xcsp3parser.dir/build
.PHONY : xcsp3parser/fast

#=============================================================================
# Target rules for targets named xcsp3parser_dynamic

# Build rule for target.
xcsp3parser_dynamic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 xcsp3parser_dynamic
.PHONY : xcsp3parser_dynamic

# fast build rule for target.
xcsp3parser_dynamic/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser_dynamic.dir/build.make CMakeFiles/xcsp3parser_dynamic.dir/build
.PHONY : xcsp3parser_dynamic/fast

#=============================================================================
# Target rules for targets named samplesXcsp3

# Build rule for target.
samplesXcsp3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 samplesXcsp3
.PHONY : samplesXcsp3

# fast build rule for target.
samplesXcsp3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/samplesXcsp3.dir/build.make CMakeFiles/samplesXcsp3.dir/build
.PHONY : samplesXcsp3/fast

samples/main.o: samples/main.cc.o
.PHONY : samples/main.o

# target to build an object file
samples/main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/samplesXcsp3.dir/build.make CMakeFiles/samplesXcsp3.dir/samples/main.cc.o
.PHONY : samples/main.cc.o

samples/main.i: samples/main.cc.i
.PHONY : samples/main.i

# target to preprocess a source file
samples/main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/samplesXcsp3.dir/build.make CMakeFiles/samplesXcsp3.dir/samples/main.cc.i
.PHONY : samples/main.cc.i

samples/main.s: samples/main.cc.s
.PHONY : samples/main.s

# target to generate assembly for a file
samples/main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/samplesXcsp3.dir/build.make CMakeFiles/samplesXcsp3.dir/samples/main.cc.s
.PHONY : samples/main.cc.s

src/UTF8String.o: src/UTF8String.cc.o
.PHONY : src/UTF8String.o

# target to build an object file
src/UTF8String.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser.dir/build.make CMakeFiles/xcsp3parser.dir/src/UTF8String.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser_dynamic.dir/build.make CMakeFiles/xcsp3parser_dynamic.dir/src/UTF8String.cc.o
.PHONY : src/UTF8String.cc.o

src/UTF8String.i: src/UTF8String.cc.i
.PHONY : src/UTF8String.i

# target to preprocess a source file
src/UTF8String.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser.dir/build.make CMakeFiles/xcsp3parser.dir/src/UTF8String.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser_dynamic.dir/build.make CMakeFiles/xcsp3parser_dynamic.dir/src/UTF8String.cc.i
.PHONY : src/UTF8String.cc.i

src/UTF8String.s: src/UTF8String.cc.s
.PHONY : src/UTF8String.s

# target to generate assembly for a file
src/UTF8String.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser.dir/build.make CMakeFiles/xcsp3parser.dir/src/UTF8String.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser_dynamic.dir/build.make CMakeFiles/xcsp3parser_dynamic.dir/src/UTF8String.cc.s
.PHONY : src/UTF8String.cc.s

src/XCSP3Code.o: src/XCSP3Code.cc.o
.PHONY : src/XCSP3Code.o

# target to build an object file
src/XCSP3Code.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser.dir/build.make CMakeFiles/xcsp3parser.dir/src/XCSP3Code.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser_dynamic.dir/build.make CMakeFiles/xcsp3parser_dynamic.dir/src/XCSP3Code.cc.o
.PHONY : src/XCSP3Code.cc.o

src/XCSP3Code.i: src/XCSP3Code.cc.i
.PHONY : src/XCSP3Code.i

# target to preprocess a source file
src/XCSP3Code.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser.dir/build.make CMakeFiles/xcsp3parser.dir/src/XCSP3Code.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser_dynamic.dir/build.make CMakeFiles/xcsp3parser_dynamic.dir/src/XCSP3Code.cc.i
.PHONY : src/XCSP3Code.cc.i

src/XCSP3Code.s: src/XCSP3Code.cc.s
.PHONY : src/XCSP3Code.s

# target to generate assembly for a file
src/XCSP3Code.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser.dir/build.make CMakeFiles/xcsp3parser.dir/src/XCSP3Code.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser_dynamic.dir/build.make CMakeFiles/xcsp3parser_dynamic.dir/src/XCSP3Code.cc.s
.PHONY : src/XCSP3Code.cc.s

src/XCSP3CoreParser.o: src/XCSP3CoreParser.cc.o
.PHONY : src/XCSP3CoreParser.o

# target to build an object file
src/XCSP3CoreParser.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser.dir/build.make CMakeFiles/xcsp3parser.dir/src/XCSP3CoreParser.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser_dynamic.dir/build.make CMakeFiles/xcsp3parser_dynamic.dir/src/XCSP3CoreParser.cc.o
.PHONY : src/XCSP3CoreParser.cc.o

src/XCSP3CoreParser.i: src/XCSP3CoreParser.cc.i
.PHONY : src/XCSP3CoreParser.i

# target to preprocess a source file
src/XCSP3CoreParser.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser.dir/build.make CMakeFiles/xcsp3parser.dir/src/XCSP3CoreParser.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser_dynamic.dir/build.make CMakeFiles/xcsp3parser_dynamic.dir/src/XCSP3CoreParser.cc.i
.PHONY : src/XCSP3CoreParser.cc.i

src/XCSP3CoreParser.s: src/XCSP3CoreParser.cc.s
.PHONY : src/XCSP3CoreParser.s

# target to generate assembly for a file
src/XCSP3CoreParser.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser.dir/build.make CMakeFiles/xcsp3parser.dir/src/XCSP3CoreParser.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser_dynamic.dir/build.make CMakeFiles/xcsp3parser_dynamic.dir/src/XCSP3CoreParser.cc.s
.PHONY : src/XCSP3CoreParser.cc.s

src/XCSP3Manager.o: src/XCSP3Manager.cc.o
.PHONY : src/XCSP3Manager.o

# target to build an object file
src/XCSP3Manager.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser.dir/build.make CMakeFiles/xcsp3parser.dir/src/XCSP3Manager.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser_dynamic.dir/build.make CMakeFiles/xcsp3parser_dynamic.dir/src/XCSP3Manager.cc.o
.PHONY : src/XCSP3Manager.cc.o

src/XCSP3Manager.i: src/XCSP3Manager.cc.i
.PHONY : src/XCSP3Manager.i

# target to preprocess a source file
src/XCSP3Manager.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser.dir/build.make CMakeFiles/xcsp3parser.dir/src/XCSP3Manager.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser_dynamic.dir/build.make CMakeFiles/xcsp3parser_dynamic.dir/src/XCSP3Manager.cc.i
.PHONY : src/XCSP3Manager.cc.i

src/XCSP3Manager.s: src/XCSP3Manager.cc.s
.PHONY : src/XCSP3Manager.s

# target to generate assembly for a file
src/XCSP3Manager.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser.dir/build.make CMakeFiles/xcsp3parser.dir/src/XCSP3Manager.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser_dynamic.dir/build.make CMakeFiles/xcsp3parser_dynamic.dir/src/XCSP3Manager.cc.s
.PHONY : src/XCSP3Manager.cc.s

src/XCSP3Tree.o: src/XCSP3Tree.cc.o
.PHONY : src/XCSP3Tree.o

# target to build an object file
src/XCSP3Tree.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser.dir/build.make CMakeFiles/xcsp3parser.dir/src/XCSP3Tree.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser_dynamic.dir/build.make CMakeFiles/xcsp3parser_dynamic.dir/src/XCSP3Tree.cc.o
.PHONY : src/XCSP3Tree.cc.o

src/XCSP3Tree.i: src/XCSP3Tree.cc.i
.PHONY : src/XCSP3Tree.i

# target to preprocess a source file
src/XCSP3Tree.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser.dir/build.make CMakeFiles/xcsp3parser.dir/src/XCSP3Tree.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser_dynamic.dir/build.make CMakeFiles/xcsp3parser_dynamic.dir/src/XCSP3Tree.cc.i
.PHONY : src/XCSP3Tree.cc.i

src/XCSP3Tree.s: src/XCSP3Tree.cc.s
.PHONY : src/XCSP3Tree.s

# target to generate assembly for a file
src/XCSP3Tree.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser.dir/build.make CMakeFiles/xcsp3parser.dir/src/XCSP3Tree.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser_dynamic.dir/build.make CMakeFiles/xcsp3parser_dynamic.dir/src/XCSP3Tree.cc.s
.PHONY : src/XCSP3Tree.cc.s

src/XCSP3TreeNode.o: src/XCSP3TreeNode.cc.o
.PHONY : src/XCSP3TreeNode.o

# target to build an object file
src/XCSP3TreeNode.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser.dir/build.make CMakeFiles/xcsp3parser.dir/src/XCSP3TreeNode.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser_dynamic.dir/build.make CMakeFiles/xcsp3parser_dynamic.dir/src/XCSP3TreeNode.cc.o
.PHONY : src/XCSP3TreeNode.cc.o

src/XCSP3TreeNode.i: src/XCSP3TreeNode.cc.i
.PHONY : src/XCSP3TreeNode.i

# target to preprocess a source file
src/XCSP3TreeNode.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser.dir/build.make CMakeFiles/xcsp3parser.dir/src/XCSP3TreeNode.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser_dynamic.dir/build.make CMakeFiles/xcsp3parser_dynamic.dir/src/XCSP3TreeNode.cc.i
.PHONY : src/XCSP3TreeNode.cc.i

src/XCSP3TreeNode.s: src/XCSP3TreeNode.cc.s
.PHONY : src/XCSP3TreeNode.s

# target to generate assembly for a file
src/XCSP3TreeNode.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser.dir/build.make CMakeFiles/xcsp3parser.dir/src/XCSP3TreeNode.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser_dynamic.dir/build.make CMakeFiles/xcsp3parser_dynamic.dir/src/XCSP3TreeNode.cc.s
.PHONY : src/XCSP3TreeNode.cc.s

src/XMLParser.o: src/XMLParser.cc.o
.PHONY : src/XMLParser.o

# target to build an object file
src/XMLParser.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser.dir/build.make CMakeFiles/xcsp3parser.dir/src/XMLParser.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser_dynamic.dir/build.make CMakeFiles/xcsp3parser_dynamic.dir/src/XMLParser.cc.o
.PHONY : src/XMLParser.cc.o

src/XMLParser.i: src/XMLParser.cc.i
.PHONY : src/XMLParser.i

# target to preprocess a source file
src/XMLParser.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser.dir/build.make CMakeFiles/xcsp3parser.dir/src/XMLParser.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser_dynamic.dir/build.make CMakeFiles/xcsp3parser_dynamic.dir/src/XMLParser.cc.i
.PHONY : src/XMLParser.cc.i

src/XMLParser.s: src/XMLParser.cc.s
.PHONY : src/XMLParser.s

# target to generate assembly for a file
src/XMLParser.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser.dir/build.make CMakeFiles/xcsp3parser.dir/src/XMLParser.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser_dynamic.dir/build.make CMakeFiles/xcsp3parser_dynamic.dir/src/XMLParser.cc.s
.PHONY : src/XMLParser.cc.s

src/XMLParserTags.o: src/XMLParserTags.cc.o
.PHONY : src/XMLParserTags.o

# target to build an object file
src/XMLParserTags.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser.dir/build.make CMakeFiles/xcsp3parser.dir/src/XMLParserTags.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser_dynamic.dir/build.make CMakeFiles/xcsp3parser_dynamic.dir/src/XMLParserTags.cc.o
.PHONY : src/XMLParserTags.cc.o

src/XMLParserTags.i: src/XMLParserTags.cc.i
.PHONY : src/XMLParserTags.i

# target to preprocess a source file
src/XMLParserTags.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser.dir/build.make CMakeFiles/xcsp3parser.dir/src/XMLParserTags.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser_dynamic.dir/build.make CMakeFiles/xcsp3parser_dynamic.dir/src/XMLParserTags.cc.i
.PHONY : src/XMLParserTags.cc.i

src/XMLParserTags.s: src/XMLParserTags.cc.s
.PHONY : src/XMLParserTags.s

# target to generate assembly for a file
src/XMLParserTags.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser.dir/build.make CMakeFiles/xcsp3parser.dir/src/XMLParserTags.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/xcsp3parser_dynamic.dir/build.make CMakeFiles/xcsp3parser_dynamic.dir/src/XMLParserTags.cc.s
.PHONY : src/XMLParserTags.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... samplesXcsp3"
	@echo "... xcsp3parser"
	@echo "... xcsp3parser_dynamic"
	@echo "... samples/main.o"
	@echo "... samples/main.i"
	@echo "... samples/main.s"
	@echo "... src/UTF8String.o"
	@echo "... src/UTF8String.i"
	@echo "... src/UTF8String.s"
	@echo "... src/XCSP3Code.o"
	@echo "... src/XCSP3Code.i"
	@echo "... src/XCSP3Code.s"
	@echo "... src/XCSP3CoreParser.o"
	@echo "... src/XCSP3CoreParser.i"
	@echo "... src/XCSP3CoreParser.s"
	@echo "... src/XCSP3Manager.o"
	@echo "... src/XCSP3Manager.i"
	@echo "... src/XCSP3Manager.s"
	@echo "... src/XCSP3Tree.o"
	@echo "... src/XCSP3Tree.i"
	@echo "... src/XCSP3Tree.s"
	@echo "... src/XCSP3TreeNode.o"
	@echo "... src/XCSP3TreeNode.i"
	@echo "... src/XCSP3TreeNode.s"
	@echo "... src/XMLParser.o"
	@echo "... src/XMLParser.i"
	@echo "... src/XMLParser.s"
	@echo "... src/XMLParserTags.o"
	@echo "... src/XMLParserTags.i"
	@echo "... src/XMLParserTags.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

